/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Counter
 */
export interface Counter {
    /**
     * 
     * @type {number}
     * @memberof Counter
     */
    id?: number;
    /**
     * 
     * @type {number}
     * @memberof Counter
     */
    count: number;
}

/**
 * Check if a given object implements the Counter interface.
 */
export function instanceOfCounter(value: object): value is Counter {
    if (!('count' in value) || value['count'] === undefined) return false;
    return true;
}

export function CounterFromJSON(json: any): Counter {
    return CounterFromJSONTyped(json, false);
}

export function CounterFromJSONTyped(json: any, ignoreDiscriminator: boolean): Counter {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'count': json['count'],
    };
}

export function CounterToJSON(value?: Counter | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'id': value['id'],
        'count': value['count'],
    };
}

